name: Dorian_Cordero
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5107411
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#15152D'
    - '#181E38'
    - '#242546'
    - '#342B57'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
